# Generated by Django 3.0.8 on 2020-09-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bid_date',
        ),
    ]
