# Generated by Django 3.0.8 on 2020-09-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_soldout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldout',
            old_name='ousername',
            new_name='username',
        ),
    ]
